### ISSUE TITLE
TODO before release

### ISSUE THREAD

**Issue by AlCatt91** [graphcore-research/kg-topology-toolbox#5]
- [ ] Integrate README?
- [x] Docs User Guide (https://github.com/graphcore-research/kg-topology-toolbox/pull/8)
- [ ] Update pip install git+ssh -> https (readme + docs + notebook)
- [ ] Update documentation link
- [x] Squash history to single commit with all co-authors?
